{
 "title": "Dashboard Alertas",
 "description": "Exibir de forma explicita dados mais relevantes",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node_id",
    "label": "Nodes",
    "query": "label_values(container_label_com_docker_swarm_node_id)"
   },
   {
    "name": "Interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Alertas",
   "type": "singlestat",
   "description": "Quantidade de alertas, apenas críticos.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "sum(count(ALERTS{alertstate=\"firing\"}) > 0) or on() vector(0)"
    }
   ]
  },
  {
   "title": "Nodes Events",
   "type": "singlestat",
   "description": "How many node are with events now.",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(ALERTS{alertname=~\"node_.*\",alertstate=\"firing\"}) or on() vector(0)"
    }
   ]
  },
  {
   "title": "Services Events",
   "type": "singlestat",
   "description": "How many services are with events now.",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(ALERTS{alertname=~\"container_.*\",alertstate=\"firing\"}) or on() vector(0)"
    }
   ]
  },
  {
   "title": "Prometheus instance down",
   "type": "singlestat",
   "description": "How many Prometheus services is down",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"InstanceDown\"}) or on() vector(0)"
    }
   ]
  },
  {
   "title": "Disks almost full",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"node_disck_space_10%\"}) or on() vector(0)"
    }
   ]
  },
  {
   "title": "Alertas",
   "type": "table",
   "description": "Listagem e descrição do alertas",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "topk(10,ALERTS{alertstate=\"firing\"})"
    }
   ]
  },
  {
   "title": "TOP 10 consumo C.P.U",
   "type": "graph",
   "description": "Top 10 container com maior consumo de C.P.U",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(irate(container_cpu_usage_seconds_total{id=~\"/docker.*\"}[10m])) by (container_label_com_docker_swarm_service_name))",
     "legendFormat": "Usando {{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "TOP 10 consumo memoria",
   "type": "graph",
   "description": "Media de consumo memoria por serviço",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(rate(container_memory_usage_bytes{container_label_com_docker_swarm_node_id=~\"$node_id\", id=~\"/docker/.*\"}[5m])) by (container_label_com_docker_swarm_service_name,name) )",
     "legendFormat": "Usando {{name}}"
    }
   ]
  }
 ]
}