version: '3.3'
services:
    clear_container:
      image: cedrotechnologies/clear_container
      hostname: '{{.Node.Hostname}}'
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
      environment:
        - "TEMPO=10800"
      deploy:
        mode: global
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s
        update_config:
          failure_action: rollback
          parallelism: 1
          delay: 10s
        resources:
          limits:
            cpus: '0.1'
            memory: 50M
